### ISSUE TITLE
Create a generic core module that manages mobile client configuration

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/tbr5-server#7]
Create a module that manages UI configuration for mobile client application, its resources, layouts (home, datagrids, detail views, forms) and allows client applications download latest versions of configuartion to render UI on mobile.

- [ ] #1 Application configuration management
- [ ] #2 Home configuration management
- [ ] #3 Datagrid configuration management
- [ ] #4 Detail View configuration management
- [ ] #5 Form configuartion management
- [ ] #6 Settings/Preferences configuration management
